package com.desapp.football_api.model.stats;

import com.desapp.football_api.model.player.Player;
import com.desapp.football_api.model.table_player_stats.PlayerTableStat;
import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.List;

import static com.desapp.football_api.utils.WhoScoredHelper.roundToTwoDecimals;

/**
 * SINGLE_TABLE inheritance for Stats hierarchy.
 * <p>
 * Expected Hibernate DDL (may vary by dialect):
 * <p>
 * create table stats (
 * id bigint generated by default as identity,
 * aerials_won_per_game double precision,
 * assists integer,
 * games integer,
 * goals integer,
 * mins integer,
 * pass_success double precision,
 * rating double precision,
 * red_cards integer,
 * shots_per_game double precision,
 * yellow_cards integer,
 * stats_type varchar(20) not null,
 * primary key (id)
 * );
 */
@ToString
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "stats", uniqueConstraints = @UniqueConstraint(columnNames = {"player_id", "stats_type"}))
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "stats_type", discriminatorType = DiscriminatorType.STRING, length = 20)
public abstract class Stats {
    @JsonBackReference
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "player_id")
    @ToString.Exclude
    private Player player;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private int games;
    private int mins;
    private int goals;
    private int assists;
    private int yellowCards;
    private int redCards;
    private double shotsPerGame;
    private double passSuccess;
    private double aerialsWonPerGame;
    private double rating;

    public Stats(List<PlayerTableStat> playerTableStats) {
        setPlayerResume(playerTableStats);
    }

    public Stats(PlayerTableStat playerTableStat) {
        this.goals = playerTableStat.getGoal();
        this.assists = playerTableStat.getAssistTotal();
        this.games = playerTableStat.getApps();
        this.mins = playerTableStat.getMinsPlayed();
        this.yellowCards = (int) playerTableStat.getYellowCard();
        this.redCards = (int) playerTableStat.getRedCard();
        this.shotsPerGame = playerTableStat.getShotsPerGame();
        this.passSuccess = playerTableStat.getPassSuccess();
        this.aerialsWonPerGame = playerTableStat.getAerialWonPerGame();
        this.rating = playerTableStat.getRating();
    }

    public void setPlayerResume(List<PlayerTableStat> playerTableStats) {
        this.games = playerTableStats.stream().mapToInt(PlayerTableStat::getApps).sum();
        this.mins = playerTableStats.stream().mapToInt(PlayerTableStat::getMinsPlayed).sum();
        this.goals = playerTableStats.stream().mapToInt(PlayerTableStat::getGoal).sum();
        this.assists = playerTableStats.stream().mapToInt(PlayerTableStat::getAssistTotal).sum();
        this.yellowCards = (int) playerTableStats.stream().mapToDouble(PlayerTableStat::getYellowCard).sum();
        this.redCards = (int) playerTableStats.stream().mapToDouble(PlayerTableStat::getRedCard).sum();

        List<PlayerTableStat> statsWithMinsForShots = playerTableStats.stream()
                .filter(stat -> stat.getMinsPlayed() > 0)
                .toList();
        double avgShots = statsWithMinsForShots.stream()
                .mapToDouble(PlayerTableStat::getShotsPerGame)
                .average()
                .orElse(0);
        this.shotsPerGame = statsWithMinsForShots.isEmpty() ? 0 : roundToTwoDecimals(avgShots);

        List<PlayerTableStat> statsWithMins = playerTableStats.stream()
                .filter(stat -> stat.getMinsPlayed() > 0)
                .toList();
        this.passSuccess = statsWithMins.isEmpty() ? 0 :
                roundToTwoDecimals(statsWithMins.stream().mapToDouble(PlayerTableStat::getPassSuccess).sum() / statsWithMins.size());

        this.aerialsWonPerGame = roundToTwoDecimals(
                playerTableStats.stream().mapToDouble(PlayerTableStat::getAerialWonPerGame).average().orElse(0)
        );
        this.rating = roundToTwoDecimals(
                playerTableStats.stream().mapToDouble(PlayerTableStat::getRating)
                        .filter(r -> r > 0).average().orElse(0)
        );
    }
}
