package com.desapp.football_api.model.stats;

import com.desapp.football_api.model.table_stats.TableStat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.List;

import static com.desapp.football_api.utils.WhoScoredHelper.roundToTwoDecimals;

/**
 * SINGLE_TABLE inheritance for Stats hierarchy.
 * <p>
 * Expected Hibernate DDL (may vary by dialect):
 * <p>
 * create table stats (
 * id bigint generated by default as identity,
 * aerials_won_per_game double precision,
 * assists integer,
 * games integer,
 * goals integer,
 * mins integer,
 * pass_success double precision,
 * rating double precision,
 * red_cards integer,
 * shots_per_game double precision,
 * yellow_cards integer,
 * stats_type varchar(20) not null,
 * primary key (id)
 * );
 */
@ToString
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "stats")
//        , uniqueConstraints = @UniqueConstraint(columnNames = {"player_id", "stats_type"}))

public abstract class Stats {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @JsonIgnore
    private Long id;

    private int games;
    private int goals;
    private int yellowCards;
    private int redCards;
    protected double shotsPerGame;
    protected double passSuccess;
    private double aerialsWonPerGame;
    private double rating;

    public Stats(List<TableStat> tableStats) {
        setPlayerResume(tableStats);
    }

    public Stats(TableStat tableStat) {
        this.goals = tableStat.getGoal();
        this.games = tableStat.getApps();
        this.yellowCards = (int) tableStat.getYellowCard();
        this.redCards = (int) tableStat.getRedCard();
        this.shotsPerGame = tableStat.getShotsPerGame();
        this.passSuccess = tableStat.getPassSuccess();
        this.aerialsWonPerGame = tableStat.getAerialWonPerGame();
        this.rating = tableStat.getRating();
    }

    public void setPlayerResume(List<TableStat> tableStats) {
        this.setResume(tableStats);
    }

    public void setResume(List<TableStat> tableStats) {
        this.games = tableStats.stream().mapToInt(TableStat::getApps).sum();
        this.goals = tableStats.stream().mapToInt(TableStat::getGoal).sum();
        this.yellowCards = (int) tableStats.stream().mapToDouble(TableStat::getYellowCard).sum();
        this.redCards = (int) tableStats.stream().mapToDouble(TableStat::getRedCard).sum();
        this.aerialsWonPerGame = roundToTwoDecimals(
                tableStats.stream().mapToDouble(TableStat::getAerialWonPerGame).average().orElse(0)
        );
        this.rating = roundToTwoDecimals(
                tableStats.stream().mapToDouble(TableStat::getRating)
                        .filter(r -> r > 0).average().orElse(0)
        );
        this.setExtraStats(tableStats);
    }

    public void setTeamResume(List<TableStat> tableStats) {
        setResume(tableStats);
    }

    public abstract void setExtraStats(List<TableStat> tableStats);

    public abstract String getPlayerLink(Long playerId);
}
