name: Run E2E Tests (scheduled)

on:
  schedule:
    - cron: '0 */23 * * *'
  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    services:
      h2:
        image: oscarfonts/h2
        ports:
          - 1521:1521
        env:
          H2_OPTIONS: "-tcp -tcpAllowOthers -tcpPort 1521 -user root -password root"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Give executions permissions to gradlew
        run: chmod +x ./gradlew

      - name: Run E2E tests only
        run: ./gradlew test --tests "com.desapp.football_api.e2e.*"
        env:
          SPRING_DATASOURCE_URL: jdbc:h2:mem:football-api;DB_CLOSE_DELAY=-1;MODE=MYSQL
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
